"""Verification_Check

Revision ID: 31ee0b3eb6f2
Revises: 
Create Date: 2026-04-22 19:36:31.682715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31ee0b3eb6f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for idempotency ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    tables = insp.get_table_names()

    if 'chat_messages' not in tables:
        op.create_table(
            'chat_messages',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('claim_id', sa.UUID(), nullable=False),
            sa.Column('role', sa.Text(), nullable=True),
            sa.Column('message', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'submissions' in tables:
        op.drop_table('submissions')

    if 'tpa_providers' in tables:
        op.drop_table('tpa_providers')

    if 'audit_logs' in tables:
        op.drop_table('audit_logs')

    # Alter workflow_state only if present
    if 'workflow_state' in tables:
        op.alter_column('workflow_state', 'current_step', existing_type=sa.TEXT(), nullable=True)
        # change status enum to text only if column exists
        cols = {c['name']: c for c in insp.get_columns('workflow_state')}
        if 'status' in cols:
            try:
                op.alter_column(
                    'workflow_state',
                    'status',
                    existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='workflow_status_enum'),
                    type_=sa.Text(),
                    nullable=True,
                )
            except Exception:
                # best-effort: if altering enum fails, skip to avoid migration stop
                pass

        # drop checkpoint_data if present
        if 'checkpoint_data' in cols:
            op.drop_column('workflow_state', 'checkpoint_data')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for idempotency ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    tables = insp.get_table_names()

    # Add checkpoint_data back if workflow_state exists
    if 'workflow_state' in tables:
        cols = {c['name']: c for c in insp.get_columns('workflow_state')}
        if 'checkpoint_data' not in cols:
            op.add_column('workflow_state', sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        # restore status enum if necessary
        if 'status' in cols:
            try:
                op.alter_column('workflow_state', 'status', existing_type=sa.Text(), type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='workflow_status_enum'), nullable=False)
            except Exception:
                pass
        op.alter_column('workflow_state', 'current_step', existing_type=sa.TEXT(), nullable=False)

    # Recreate audit_logs / tpa_providers / submissions if missing
    if 'audit_logs' not in tables:
        op.create_table(
            'audit_logs',
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('claim_id', sa.UUID(), autoincrement=False, nullable=True),
            sa.Column('actor', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
            sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
            sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('audit_logs_claim_id_fkey'), ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey')),
        )

    if 'tpa_providers' not in tables:
        op.create_table(
            'tpa_providers',
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
            sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
            sa.Column('logo', sa.TEXT(), server_default=sa.text("'??'::text"), autoincrement=False, nullable=True),
            sa.Column('provider_type', sa.TEXT(), server_default=sa.text("'Private'::text"), autoincrement=False, nullable=True),
            sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('tpa_providers_pkey')),
            sa.UniqueConstraint('code', name=op.f('tpa_providers_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
        )

    if 'submissions' not in tables:
        op.create_table(
            'submissions',
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('claim_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('payer', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
            sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
            sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
            sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_submission'), ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name=op.f('submissions_pkey')),
        )

    if 'chat_messages' in tables:
        op.drop_table('chat_messages')

    # ### end Alembic commands ###
